import Image from 'next/image';
import Link from 'next/link';
import Head from 'next/head';
import Script from 'next/script';
import TopSlider from '../../components/TopSlider/topslider'
import Content from '../../components/DestinationContent/content'
import layout from '../../styles/Layout.module.scss';

export default function Destination() {
  return (
    <div className={layout.container}>
      <Head>
        <title>Telturer.no</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      </Head>
      <main>
        <TopSlider/>
        <Content/>
        
      </main>
    </div>
  );
}
